import { createElement } from "react";
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";
import { ArrowRight, BarChart3, CalendarDays, Check, CheckSquare2, ChevronDown, FolderKanban, Moon, ShieldCheck, Timer, Zap } from "lucide-react";
import productivityArtwork from "../assets/SmartProductivityimages.png";

const features = [
  { icon: CheckSquare2, title: "Tasks that feel manageable", description: "Break study goals into clear next steps, add due dates, and see progress as it happens." },
  { icon: FolderKanban, title: "Projects with a purpose", description: "Group related work, keep priorities visible, and understand what is moving forward." },
  { icon: Timer, title: "Focus without guesswork", description: "Use a flexible Pomodoro timer and save completed focus sessions to your history." },
  { icon: BarChart3, title: "Progress you can use", description: "Review your study patterns and task completion with personal analytics." },
  { icon: CalendarDays, title: "A clear view of your week", description: "See deadlines in context and plan around the time you actually have." },
  { icon: Moon, title: "Comfortable day or night", description: "Choose light, dark, or system theme and keep the interface comfortable." },
];

const faqs = [
  ["Is SmartProductivity free to start?", "Yes. The free plan includes task planning, projects, focus sessions, and limited analytics history. Plan limits are shown in the app."],
  ["Can I use it on my phone?", "Yes. The app adapts to mobile, tablet, and desktop layouts. Your account data is stored in the connected MongoDB database."],
  ["How does the focus timer work?", "Choose a focus or break interval, start the timer, and link a task if you want. Completed focus sessions are saved to your history."],
  ["How do paid plans work?", "Paid plans use Stripe Checkout when the owner has configured Stripe keys and price IDs. You can review availability on the pricing page."],
];

function Landing() {
  const { token } = useSelector((state) => state.auth);
  const destination = token ? "/dashboard" : "/register";

  return (
    <main className="min-h-screen overflow-hidden bg-white text-slate-900 dark:bg-slate-950 dark:text-white">
      <header className="relative z-10 border-b border-slate-200/70 bg-white/90 backdrop-blur dark:border-slate-800 dark:bg-slate-950/85">
        <div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link to="/" aria-label="SmartProductivity home"><img src="/SmartProductivity%20logo.png" alt="SmartProductivity" className="h-11 w-40 rounded-md bg-white object-contain" /></Link>
          <nav aria-label="Main navigation" className="hidden items-center gap-8 text-sm font-medium text-slate-600 dark:text-slate-300 md:flex"><a className="hover:text-indigo-600 dark:hover:text-indigo-300" href="#features">Features</a><a className="hover:text-indigo-600 dark:hover:text-indigo-300" href="#how-it-works">How it works</a><Link className="hover:text-indigo-600 dark:hover:text-indigo-300" to="/pricing">Pricing</Link></nav>
          <div className="flex items-center gap-2 sm:gap-3"><Link to={token ? "/dashboard" : "/login"} className="hidden rounded-xl px-3 py-2 text-sm font-semibold text-slate-700 no-underline hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-800 sm:inline-flex">{token ? "Dashboard" : "Sign in"}</Link><Link to={destination} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white no-underline shadow-lg shadow-indigo-600/20 transition hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:focus:ring-offset-slate-950 sm:px-5">{token ? "Open app" : "Start for free"}<ArrowRight size={16} aria-hidden="true" /></Link></div>
        </div>
      </header>

      <section className="relative isolate px-4 pb-16 pt-16 sm:px-6 sm:pt-24 lg:px-8 lg:pb-24 lg:pt-28">
        <div aria-hidden="true" className="absolute inset-x-0 top-0 -z-10 h-[540px] bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-100 via-white to-white dark:from-indigo-950/70 dark:via-slate-950 dark:to-slate-950" />
        <div className="mx-auto max-w-5xl text-center"><div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-white/80 px-3 py-1.5 text-xs font-semibold text-indigo-800 shadow-sm dark:border-indigo-900 dark:bg-slate-900/80 dark:text-indigo-200 sm:text-sm"><Zap size={15} aria-hidden="true" /> A calmer way to make progress</div><h1 className="mx-auto max-w-4xl text-4xl font-bold leading-[1.1] tracking-tight text-slate-950 dark:text-white sm:text-6xl lg:text-7xl">Plan Better.<br className="hidden sm:block" /> <span className="bg-gradient-to-r from-indigo-600 to-violet-600 bg-clip-text text-transparent dark:from-indigo-300 dark:to-violet-300">Focus Deeper. Achieve More.</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-600 dark:text-slate-300 sm:text-lg sm:leading-8">Bring tasks, projects, study sessions, and weekly progress into one thoughtful workspace. Make a plan you can follow, then focus on one thing at a time.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to={destination} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-6 text-sm font-semibold text-white no-underline shadow-xl shadow-indigo-600/20 transition hover:-translate-y-0.5 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:focus:ring-offset-slate-950">Start for Free <ArrowRight size={17} aria-hidden="true" /></Link><a href="#features" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-300 bg-white/70 px-6 text-sm font-semibold text-slate-800 no-underline transition hover:border-indigo-300 hover:bg-white dark:border-slate-700 dark:bg-slate-900/70 dark:text-slate-100">Explore Features</a></div><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Free to start · No card needed · Your progress stays yours</p></div>
        <figure className="relative mx-auto mt-14 max-w-6xl overflow-hidden rounded-[28px] border border-slate-200/80 bg-white p-2 shadow-2xl shadow-indigo-950/10 dark:border-slate-800 dark:bg-slate-900 sm:mt-20 sm:p-3"><div aria-hidden="true" className="absolute -inset-x-12 -top-20 -z-10 h-64 rounded-full bg-indigo-300/30 blur-3xl dark:bg-indigo-800/20" /><img src={productivityArtwork} alt="SmartProductivity illustrations for planning, study workflows, and focus" className="block h-auto w-full rounded-[20px]" fetchPriority="high" /><figcaption className="sr-only">SmartProductivity workspace artwork representing planning, projects, and focus.</figcaption></figure>
      </section>

      <section id="features" className="scroll-mt-20 border-y border-slate-100 bg-slate-50/80 px-4 py-16 dark:border-slate-800 dark:bg-slate-900/50 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Everything in one place" title="Build a routine that works for you" description="Small, connected tools help turn a busy list into a plan you can act on." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(({ icon, title, description }) => <article key={title} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg hover:shadow-indigo-950/5 dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-50 text-indigo-700 transition group-hover:bg-indigo-600 group-hover:text-white dark:bg-indigo-950/70 dark:text-indigo-300">{createElement(icon, { size: 21, strokeWidth: 1.8, "aria-hidden": true })}</div><h3 className="text-base font-semibold text-slate-900 dark:text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{description}</p></article>)}</div></div></section>

      <section id="how-it-works" className="scroll-mt-20 px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-indigo-600 dark:text-indigo-300">A simple daily loop</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-4xl">Make space for the work that matters.</h2><p className="mt-4 max-w-xl text-base leading-7 text-slate-600 dark:text-slate-300">Start with a short plan. Give important work a focused block. Use your history to adjust tomorrow, without adding another complicated system.</p><Link to={destination} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-indigo-700 no-underline hover:gap-3 dark:text-indigo-300">Plan your first day <ArrowRight size={16} aria-hidden="true" /></Link></div><div className="grid gap-4 sm:grid-cols-2">{[["01", "Choose the next step", "Turn a larger goal into a task you can start."], ["02", "Set a focus block", "Pick an interval and keep distractions out of the way."], ["03", "Save what you finish", "Link your focus session to a task or project."], ["04", "Reflect and adapt", "Use your own activity to plan the next week."]].map(([step, title, copy]) => <div key={step} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><span className="text-xs font-bold tracking-widest text-indigo-600 dark:text-indigo-300">STEP {step}</span><h3 className="mt-3 font-semibold text-slate-900 dark:text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{copy}</p></div>)}</div></div></section>

      <section className="border-y border-slate-100 bg-indigo-50/60 px-4 py-14 dark:border-slate-800 dark:bg-indigo-950/20 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto grid max-w-6xl gap-8 text-center sm:grid-cols-3 sm:text-left">{[[Check, "A plan you can see", "Tasks, deadlines, and projects stay together."], [Timer, "Focus you can track", "Completed sessions add to your own history."], [ShieldCheck, "Your account, your data", "Each person sees their own productivity workspace."]].map(([icon, title, copy]) => <div key={title} className="flex flex-col items-center gap-3 sm:items-start">{createElement(icon, { className: "text-indigo-600 dark:text-indigo-300", size: 22, "aria-hidden": true })}<h3 className="font-semibold text-slate-900 dark:text-white">{title}</h3><p className="max-w-xs text-sm leading-6 text-slate-600 dark:text-slate-300">{copy}</p></div>)}</div></section>

      <section className="px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto max-w-5xl rounded-3xl border border-indigo-100 bg-gradient-to-br from-indigo-50 to-violet-50 p-7 dark:border-indigo-900/60 dark:from-slate-900 dark:to-indigo-950/40 sm:p-12"><p className="text-xs font-bold uppercase tracking-[0.16em] text-indigo-700 dark:text-indigo-300">A sample workflow</p><blockquote className="mt-4 max-w-3xl text-xl font-semibold leading-8 text-slate-900 dark:text-white sm:text-2xl">“I can see what needs attention, start a focus session, and finish the day knowing what moved forward.”</blockquote><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">Illustrative example · Not a customer testimonial</p></div></section>

      <section className="px-4 pb-16 sm:px-6 sm:pb-24 lg:px-8"><div className="mx-auto max-w-7xl rounded-[28px] bg-slate-950 px-6 py-12 text-white dark:bg-indigo-950 sm:px-10 lg:flex lg:items-center lg:justify-between lg:px-14 lg:py-14"><div><p className="text-sm font-semibold text-indigo-300">Start small. Stay consistent.</p><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">Make your next study session count.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Create a free workspace, add a task, and start with one focus block.</p></div><div className="mt-7 flex flex-col gap-3 sm:flex-row lg:mt-0"><Link to={destination} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-semibold text-indigo-800 no-underline transition hover:bg-indigo-50">Start for free <ArrowRight size={16} aria-hidden="true" /></Link><Link to="/pricing" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/25 px-5 text-sm font-semibold text-white no-underline transition hover:bg-white/10">View plans</Link></div></div></section>

      <section className="border-t border-slate-100 bg-slate-50/70 px-4 py-16 dark:border-slate-800 dark:bg-slate-900/40 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><SectionHeading eyebrow="Questions" title="A few useful details" description="A quick overview before you get started." /><div className="mt-9 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white px-5 dark:divide-slate-800 dark:border-slate-800 dark:bg-slate-900 sm:px-7">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-slate-900 outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-white"><span>{question}</span><ChevronDown className="shrink-0 text-slate-500 transition group-open:rotate-180" size={18} aria-hidden="true" /></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">{answer}</p></details>)}</div></div></section>

      <footer className="px-4 py-8 dark:bg-slate-950 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 border-t border-slate-200 pt-6 text-sm text-slate-500 dark:border-slate-800 dark:text-slate-400 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><img src="/SmartProductivity%20logo.png" alt="" className="h-8 w-28 rounded bg-white object-contain" /><span>Plan Better. Focus Deeper. Achieve More.</span></div><nav aria-label="Footer navigation" className="flex flex-wrap gap-x-5 gap-y-2"><Link to="/pricing" className="text-inherit no-underline hover:text-indigo-600 dark:hover:text-indigo-300">Pricing</Link><Link to="/login" className="text-inherit no-underline hover:text-indigo-600 dark:hover:text-indigo-300">Sign in</Link><Link to="/register" className="text-inherit no-underline hover:text-indigo-600 dark:hover:text-indigo-300">Create account</Link></nav></div></footer>
    </main>
  );
}

function SectionHeading({ eyebrow, title, description }) {
  return <header className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[0.17em] text-indigo-600 dark:text-indigo-300">{eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-4xl">{title}</h2><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300 sm:text-base">{description}</p></header>;
}

export default Landing;
